swagger: "2.0"
info:
  title: No more flex
  version: 0.0.1
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /transactions/add:
    post:
      summary: Add new transaction
      operationId: addTransaction
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/transaction"
      responses:
        201:
          description: created
        default:
          description: generic server error
          schema:
            $ref: "#/definitions/error"
  /transactions/filter:
    get:
      summary: Filter transactions
      operationId: filterTransactions
      parameters:
        - name: category
          in: query
          type: string
        - name: receiver
          in: query
          type: string
        - name: sender
          in: query
          type: string
        - name: from
          in: query
          type: integer
          format: int64
        - name: to
          in: query
          type: integer
          format: int64
      responses:
        200:
          description: list of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/transaction'
        default:
          description: generic server error
          schema:
            $ref: "#/definitions/error"
definitions:
  transaction:
    type: object
    required:
      - sender
      - receiver
      - value
      - time
    properties:
      sender:
        type: string
      receiver:
        type: string
      value:  
        type: integer
        format: int64
      time:
        type: integer
        format: int64
      category:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string


