// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddTransactionHandlerFunc turns a function with the right signature into a add transaction handler
type AddTransactionHandlerFunc func(AddTransactionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddTransactionHandlerFunc) Handle(params AddTransactionParams) middleware.Responder {
	return fn(params)
}

// AddTransactionHandler interface for that can handle valid add transaction params
type AddTransactionHandler interface {
	Handle(AddTransactionParams) middleware.Responder
}

// NewAddTransaction creates a new http.Handler for the add transaction operation
func NewAddTransaction(ctx *middleware.Context, handler AddTransactionHandler) *AddTransaction {
	return &AddTransaction{Context: ctx, Handler: handler}
}

/*AddTransaction swagger:route POST /transactions/add addTransaction

Add new transaction

*/
type AddTransaction struct {
	Context *middleware.Context
	Handler AddTransactionHandler
}

func (o *AddTransaction) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddTransactionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
