// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pl0q1n/No_More_Flex/models"
)

// AddTransactionCreatedCode is the HTTP code returned for type AddTransactionCreated
const AddTransactionCreatedCode int = 201

/*AddTransactionCreated created

swagger:response addTransactionCreated
*/
type AddTransactionCreated struct {
}

// NewAddTransactionCreated creates AddTransactionCreated with default headers values
func NewAddTransactionCreated() *AddTransactionCreated {

	return &AddTransactionCreated{}
}

// WriteResponse to the client
func (o *AddTransactionCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*AddTransactionDefault generic server error

swagger:response addTransactionDefault
*/
type AddTransactionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddTransactionDefault creates AddTransactionDefault with default headers values
func NewAddTransactionDefault(code int) *AddTransactionDefault {
	if code <= 0 {
		code = 500
	}

	return &AddTransactionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add transaction default response
func (o *AddTransactionDefault) WithStatusCode(code int) *AddTransactionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add transaction default response
func (o *AddTransactionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add transaction default response
func (o *AddTransactionDefault) WithPayload(payload *models.Error) *AddTransactionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add transaction default response
func (o *AddTransactionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddTransactionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
