// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pl0q1n/No_More_Flex/models"
)

// FilterTransactionsOKCode is the HTTP code returned for type FilterTransactionsOK
const FilterTransactionsOKCode int = 200

/*FilterTransactionsOK list of transactions

swagger:response filterTransactionsOK
*/
type FilterTransactionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Transaction `json:"body,omitempty"`
}

// NewFilterTransactionsOK creates FilterTransactionsOK with default headers values
func NewFilterTransactionsOK() *FilterTransactionsOK {

	return &FilterTransactionsOK{}
}

// WithPayload adds the payload to the filter transactions o k response
func (o *FilterTransactionsOK) WithPayload(payload []*models.Transaction) *FilterTransactionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the filter transactions o k response
func (o *FilterTransactionsOK) SetPayload(payload []*models.Transaction) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FilterTransactionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Transaction, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*FilterTransactionsDefault generic server error

swagger:response filterTransactionsDefault
*/
type FilterTransactionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFilterTransactionsDefault creates FilterTransactionsDefault with default headers values
func NewFilterTransactionsDefault(code int) *FilterTransactionsDefault {
	if code <= 0 {
		code = 500
	}

	return &FilterTransactionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the filter transactions default response
func (o *FilterTransactionsDefault) WithStatusCode(code int) *FilterTransactionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the filter transactions default response
func (o *FilterTransactionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the filter transactions default response
func (o *FilterTransactionsDefault) WithPayload(payload *models.Error) *FilterTransactionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the filter transactions default response
func (o *FilterTransactionsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FilterTransactionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
