version: "3.1"
services:

  db:
    image: "postgres:12"
    container_name: "nmf_postgres"
    restart: always
    ports:
      - "54320:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data


volumes:
  dbdata: